// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
const LIMIT : u32 = 4000000;

fn main() {
    let mut a : u32 = 1;
    let mut b : u32 = 2;

    let mut result : u32 = 0;

    loop {
        if a % 2 == 0 {
            result += a;
        }
        if a > LIMIT {
            break;
        }

        let tmp = a;
        a = b;
        b = tmp + b;
    }

    println!("{}", result);
}
