[package]
name = "XOR_decryption"
version = "0.1.0"
authors = ["irevoire <irevoire@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
itertools = "*"
